# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sphinx Documentation CI

on:
  push:
    branches: 
      - main
      - master
    paths:
      - 'docs/**'
      - 'doc/**'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'docs/**'
      - 'doc/**'


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          python3 -m pip install setuptools wheel
          python3 -m pip install -r requirements-dev.txt
          python3 -m pip install -r requirements.txt
          cd docs/
          make openapi_spec.yml
          make html

      - name: Deploy 🚀
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@3.5.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # The branch the action should deploy to.
          FOLDER: docs/build/html  # The folder the action should deploy.